# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_rename_course_code_to_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_code',
        ),
    ]
