# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_remove_subject_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='live_id',
        ),
    ]
