# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_remove_live_id_from_course_and_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.Campus'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(default='DEV101', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(default='Software Development 101', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='search',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
