# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_remove_core_keyword_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
