# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_make_subject_duration_and_time_optional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='uni',
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=21),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
