# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0008_add_course_to_universities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='added_user',
            new_name='user',
        ),
    ]
