# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 05:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20170208_0542'),
        ('groups', '0004_group_student_can_join_not_required'),
    ]

    operations = [
    ]
