# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_merge_20170208_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='privacy',
            new_name='private',
        ),
        migrations.RenameField(
            model_name='customgroup',
            old_name='privacy',
            new_name='private',
        ),
        migrations.RenameField(
            model_name='mentorsgroup',
            old_name='privacy',
            new_name='private',
        ),
        migrations.RenameField(
            model_name='studentservicesgroup',
            old_name='privacy',
            new_name='private',
        ),
        migrations.RenameField(
            model_name='studygroup',
            old_name='privacy',
            new_name='private',
        ),
    ]
