# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_rename_groups_privacy_to_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='event_ticketing',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='membership_payment',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='membership_status',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='club',
            name='short_name',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='club',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
