# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_set_club_field_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
