# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 05:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_set_club_member_membership_to_allow_null'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentServicesGroup',
            new_name='StudentService',
        ),
        migrations.RenameModel(
            old_name='ServiceAdmin',
            new_name='StudentServiceAdmin',
        ),
        migrations.RenameModel(
            old_name='ServiceDropinDetail',
            new_name='StudentServiceDropin',
        ),
        migrations.RenameModel(
            old_name='ServiceEvent',
            new_name='StudentServiceEvent',
        ),
        migrations.RenameModel(
            old_name='ServiceEventMember',
            new_name='StudentServiceEventMember',
        ),
        migrations.RenameModel(
            old_name='ServiceMember',
            new_name='StudentServiceMember',
        ),
    ]
