# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0010_rename_student_service_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentservice',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentservice',
            name='phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentservice',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
