# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 23:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0011_set_student_service_default_values'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MentorsGroup',
            new_name='MentorGroup',
        ),
        migrations.RenameModel(
            old_name='MentorsGroupMember',
            new_name='MentorGroupMember',
        ),
    ]
