# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0012_rename_mentors_group_to_mentor_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='faculty',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='customgroup',
            old_name='faculty',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='mentorgroup',
            old_name='faculty',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='studentservice',
            old_name='faculty',
            new_name='school',
        ),
        migrations.RenameField(
            model_name='studygroup',
            old_name='faculty',
            new_name='school',
        ),
    ]
