# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0013_rename_faculty_to_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentserviceadmin',
            old_name='service_page',
            new_name='student_service',
        ),
        migrations.RenameField(
            model_name='studentservicedropin',
            old_name='service_page',
            new_name='student_service',
        ),
        migrations.RenameField(
            model_name='studentserviceevent',
            old_name='service_page',
            new_name='student_service',
        ),
        migrations.RenameField(
            model_name='studentservicemember',
            old_name='service_page',
            new_name='student_service',
        ),
    ]
