# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0014_rename_service_page_to_student_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='club',
            name='owner_manage_members',
            field=models.BooleanField(default=False),
        ),
    ]
