# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0015_change_two_group_fields_to_boolean'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='picture_thumb',
            new_name='thumbnail_pic',
        ),
        migrations.RenameField(
            model_name='customgroup',
            old_name='cover_picture',
            new_name='banner_pic',
        ),
        migrations.RemoveField(
            model_name='club',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='customgroup',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='mentorgroup',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='studentservice',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='studygroup',
            name='picture',
        ),
        migrations.AddField(
            model_name='club',
            name='banner_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mentorgroup',
            name='banner_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studentservice',
            name='banner_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='banner_pic',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
