# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0016_rename_image_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubmember',
            old_name='club',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='customgroupmember',
            old_name='customgroups',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='mentorgroupmember',
            old_name='mentor',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentservicemember',
            old_name='student_service',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studygroupmember',
            old_name='study_group',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='customgroupmember',
            name='member_type',
            field=models.IntegerField(null=True),
        ),
    ]
