# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0017_rename_clubmember_club_to_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubadmin',
            old_name='club',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentserviceadmin',
            old_name='student_service',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='mentorgroup',
            name='addable_mentees',
            field=models.IntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorgroup',
            name='count_mentees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentorgroup',
            name='find_mentor',
            field=models.SmallIntegerField(default=False),
        ),
        migrations.AlterField(
            model_name='mentorgroupmember',
            name='types',
            field=models.IntegerField(default=0),
        ),
    ]
