# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0018_rename_some_group_member_columns'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentservicedropin',
            old_name='student_service',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='studentserviceevent',
            old_name='student_service',
            new_name='group',
        ),
    ]
