# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0019_rename_student_service_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='club',
            name='uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customgroup',
            name='uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorgroup',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mentorgroup',
            name='uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentservice',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentservice',
            name='uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studygroup',
            name='uni',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
    ]
