# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 13:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0020_make_group_name_and_uni_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentorgroup',
            name='group_name',
        ),
    ]
