# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0021_remove_multiple_group_names_from_mentorgroups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='purpose',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
