# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0022_set_studygroup_purpose_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorgroup',
            name='program_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
