# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 06:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0023_add_program_name_to_mentor_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubmember',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='customgroupmember',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='mentorgroupmember',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='studentservicemember',
            unique_together=set([('group', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='studygroupmember',
            unique_together=set([('group', 'user')]),
        ),
    ]
