# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0025_creator_required_when_creating_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubmember',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='customgroupmember',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='mentorgroupmember',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='studentservicemember',
            unique_together=set([]),
        ),
        migrations.AlterUniqueTogether(
            name='studygroupmember',
            unique_together=set([]),
        ),
    ]
