# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0027_make_group_one_to_one_keys_regular_foriegns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='event_ticketing',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='membership_payment',
            field=models.CharField(default='Y', max_length=1),
        ),
        migrations.AlterField(
            model_name='club',
            name='membership_status',
            field=models.CharField(default='Y', max_length=1),
        ),
    ]
