# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 05:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universities', '0007_remove_live_id_from_course_and_school'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0005_remove_live_id_from_course_and_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notify_all', models.BooleanField(default=False)),
                ('word', models.CharField(max_length=40)),
                ('subject',
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                        related_name='subject', to='subjects.Subject')),
                ('uni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uni', to='universities.University')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('word',),
            },
        ),
    ]
