# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_item_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_name',
            new_name='photo',
        ),
    ]
