# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_rename_marketplace_item_name_to_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='types',
            new_name='category',
        ),
    ]
