# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('prefer not to say', 'prefer not to say')], default=None, max_length=6, null=True),
        ),
#        migrations.RunPython(load_initial_data),
    ]
