# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 00:14
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', "0003_use django's groups"),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
