# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='prefered_email',
            new_name='preferred_email',
        ),
    ]
