# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        #('groups', '__latest__'),
        ('users', '0004_user_faculty'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='nonmember',
#            name='service_page_id',
#            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.StudentServicesGroup'),
#        ),
    ]
