# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_keyword_non_ucroo'),
        ('users', '0005_nonucroomember_service_page_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
#        migrations.RemoveField(
#            model_name='nonucroomember',
#            name='service_page_id',
#        ),
        migrations.DeleteModel(
            name='NonUcrooMember',
        ),
    ]
