# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_fix_preferred_email_spelling'),
        ('users', '0006_auto_20170206_0459'),
    ]

    operations = [
    ]
