# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_merge_20170206_2323'),
        ('users', '0007_merge_20170206_2255'),
    ]

    operations = [
    ]
