# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 05:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20170207_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='unread_notifications',
        ),
    ]
