# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_unread_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_id', models.IntegerField(blank=True, null=True)),
                ('parent_id', models.IntegerField()),
                ('profile_key', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_value', models.CharField(blank=True, max_length=5000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
