# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_userprofiledetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledetail',
            name='profile_type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
