# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 03:14
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userprofiledetail_profile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledetail',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
        migrations.AddField(
            model_name='userprofiledetail',
            name='modified',
            field=model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified'),
        ),
    ]
