# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20170209_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='faculty',
            new_name='school',
        ),
    ]
