# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 23:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_change_users_school_to_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uni',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
        ),
    ]
