# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_verificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='cover_picture',
            new_name='cover_pic',
        ),
    ]
