# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20170306_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilecategory',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userprofilecategory',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='userprofiledetail',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='userprofiledetail',
            name='date_modified',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other'), ('prefer not to say', 'prefer not to say')], default=None, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_email',
            field=models.CharField(blank=True, choices=[('primary', 'primary'), ('secondary', 'secondary')], default='primary', max_length=200, null=True),
        ),
    ]
