# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_adjust_connection_statuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='name',
        ),
    ]
