# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_rename_username_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together=set([('from_user', 'to_user')]),
        ),
    ]
