# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_file', '0002_fileupload_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='username',
            new_name='user',
        ),
    ]
