# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-24 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='activitytransaction',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activitytransaction',
            name='user_to',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='ActivityTransaction',
        ),
    ]
