# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studytimer', '0002_entry_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='status',
        ),
        migrations.AddField(
            model_name='entry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
