# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studytimer', '0003_rename_studytimer_status_to_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='is_active',
            new_name='active',
        ),
    ]
