# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 07:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studytimer', '0004_rename_studytimer_is_active_to_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='uni',
        ),
    ]
