# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_remove_prefix_from_post_attributes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
    ]
