# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_rename_faculty_to_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttag',
            name='tag',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
