# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0010_change_reported_post_to_post_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='post',
            name='html',
        ),
    ]
