# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0011_rename_post_html_to_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('reported', 'Reported'), ('cleared', 'Cleared'), ('userdeleted', 'Deleted by user'), ('admindeleted', 'Deleted by admin')], default='created', max_length=20),
        ),
        migrations.AlterField(
            model_name='postlog',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('reported', 'Reported'), ('cleared', 'Cleared'), ('edited', 'Edited'), ('userdeleted', 'Deleted by user')], default='created', max_length=20),
        ),
    ]
