# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 02:23
from __future__ import unicode_literals

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0012_adjust_post_and_postlog_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlog',
            name='action',
        ),
        migrations.AddField(
            model_name='post',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AddField(
            model_name='postlog',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='posted', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AddField(
            model_name='postlog',
            name='status_changed',
            field=model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='posted', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
