# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0013_use_statusmodel_on_post_and_postlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlog',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
    ]
