# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_remove_postlog_comment_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
