# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0009_add_course_to_universities'),
        ('feeds', '0016_add_post_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='universities.Course'),
        ),
    ]
