# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0017_add_course_to_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='targeting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
