# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0019_add_feed_posts_meta_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='last_id',
            field=models.IntegerField(null=True),
        ),
    ]
