# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 05:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feeds', '0020_make_follower_last_id_optional'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('feed_object', 'feed_object_id', 'user')]),
        ),
    ]
