# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0021_add_unique_contraints_to_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='posted', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(blank=True, default='post', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='postlog',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='posted', max_length=100, no_check_for_status=True, verbose_name='status'),
        ),
    ]
