# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0022_adjust_status_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='follower',
            name='user',
        ),
        migrations.DeleteModel(
            name='Follower',
        ),
    ]
