# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 09:07
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='side_menu',
            field=jsonfield.fields.JSONField(default=[{'location': 'club', 'title': 'Clubs & Societies'}, {'location': 'unit', 'title': 'Subjects'}, {'location': 'study_group', 'title': 'Study'}, {'location': 'service_page', 'title': 'Student Services'}, {'location': 'mentors', 'title': 'Mentors'}, {'location': 'customgroups', 'title': 'Custom'}]),
        ),
    ]
