# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_fix side menu jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='side_menu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[{'location': 'club', 'title': 'Clubs & Societies'}, {'location': 'unit', 'title': 'Subjects'}, {'location': 'study_group', 'title': 'Study'}, {'location': 'service_page', 'title': 'Student Services'}, {'location': 'mentors', 'title': 'Mentors'}, {'location': 'customgroups', 'title': 'Custom'}]),
        ),
    ]
