# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 22:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0004_rename_side_menu_to_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='menu',
        ),
    ]
