# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 03:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0006_rename_faculty_to_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='live_id',
        ),
    ]
