# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 03:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0007_remove_live_id_from_course_and_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
