# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0010_make_universities_name_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='uni',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='uni',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='universities.University'),
            preserve_default=False,
        ),
    ]
