# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0011_make_uni_and_name_required_for_course_and_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
