# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 17:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0012_make_course_code_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
