# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170120_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='unit_id',
            new_name='subject_id',
        ),
    ]
