# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 04:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_unit_to_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keyword',
            name='non_ucroo',
        ),
    ]
