# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20170206_0459'),
        ('core', '0004_remove_keyword_non_ucroo'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='non_ucroo_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.NonMember'),
        ),
    ]
