# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_keyword_non_ucroo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='subject_id',
            new_name='subject',
        ),
    ]
