# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_id_from_field_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_active',
            new_name='active',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='category_name',
            new_name='module',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='module_name',
            new_name='name',
        ),
    ]
