# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_message_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ucroo_attachment_id',
        ),
    ]
