# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0004_rename_ids_to_no_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user',
            new_name='sender',
        ),
    ]
