# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0007_rebuild_conversations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='users',
            new_name='members',
        ),
    ]
